"""Latest completed workout route map exposed by ATHLTH."""

from __future__ import annotations

import base64
import binascii

from homeassistant.components.camera import Camera
from homeassistant.config_entries import ConfigEntry
from homeassistant.core import HomeAssistant
from homeassistant.helpers.device_registry import DeviceInfo
from homeassistant.helpers.dispatcher import async_dispatcher_connect
from homeassistant.helpers.entity_platform import AddConfigEntryEntitiesCallback

from .const import (
    DATA_RUNTIMES,
    DOMAIN,
    signal_client_added,
    signal_update,
)
from .runtime import ATHLTHClientRuntime, ATHLTHRuntimeData


async def async_setup_entry(
    hass: HomeAssistant,
    entry: ConfigEntry,
    async_add_entities: AddConfigEntryEntitiesCallback,
) -> None:
    """Set up the latest workout route camera for every paired client."""
    runtime: ATHLTHRuntimeData = hass.data[DOMAIN][DATA_RUNTIMES][
        entry.entry_id
    ]
    added_clients: set[str] = set()

    def add_client(client_id: str) -> None:
        client = runtime.clients.get(client_id)
        if client is None or client_id in added_clients:
            return

        added_clients.add(client_id)
        async_add_entities(
            [ATHLTHWorkoutRouteCamera(entry, runtime, client)]
        )

    for client in runtime.public_clients():
        add_client(client.client_id)

    entry.async_on_unload(
        async_dispatcher_connect(
            hass,
            signal_client_added(entry.entry_id),
            add_client,
        )
    )


class ATHLTHWorkoutRouteCamera(Camera):
    """Camera entity containing the map generated by ATHLTH on iPhone."""

    _attr_has_entity_name = True
    _attr_name = "Last workout route"
    _attr_icon = "mdi:map-marker-path"
    _attr_should_poll = False
    _attr_content_type = "image/jpeg"
    _attr_is_on = True

    def __init__(
        self,
        entry: ConfigEntry,
        runtime: ATHLTHRuntimeData,
        client: ATHLTHClientRuntime,
    ) -> None:
        super().__init__()
        self._entry_id = entry.entry_id
        self._runtime = runtime
        self._client = client

        if client.is_primary:
            unique_prefix = entry.entry_id
            device_identifier = entry.entry_id
            device_name = "ATHLTH"
        else:
            unique_prefix = f"{entry.entry_id}_{client.client_id}"
            device_identifier = f"{entry.entry_id}:{client.client_id}"
            suffix = client.client_id[-4:]
            device_name = f"{client.name} · {suffix}"

        self._attr_unique_id = f"{unique_prefix}_last_workout_route"
        self._attr_device_info = DeviceInfo(
            identifiers={(DOMAIN, device_identifier)},
            name=device_name,
            manufacturer="ATHLTH",
            model="Home Assistant Link",
        )

    @property
    def available(self) -> bool:
        """Return whether a completed workout map has been received."""
        value = self._client.state.get(
            "last_workout_route_map_base64"
        )
        return isinstance(value, str) and bool(value)

    async def async_camera_image(
        self,
        width: int | None = None,
        height: int | None = None,
    ) -> bytes | None:
        """Return the latest completed route map JPEG."""
        encoded = self._client.state.get(
            "last_workout_route_map_base64"
        )
        if not isinstance(encoded, str) or not encoded:
            return None

        try:
            return base64.b64decode(
                encoded,
                validate=True,
            )
        except (ValueError, binascii.Error):
            return None

    @property
    def extra_state_attributes(self):
        """Expose useful metadata alongside the image."""
        state = self._client.state
        attributes = {
            "workout": state.get("last_workout_route_name"),
            "type": state.get("last_workout_route_type"),
            "started_at": state.get("last_workout_route_started_at"),
            "ended_at": state.get("last_workout_route_ended_at"),
            "duration_seconds": state.get(
                "last_workout_route_duration_seconds"
            ),
            "distance_meters": state.get(
                "last_workout_route_distance_meters"
            ),
            "elevation_gain_meters": state.get(
                "last_workout_elevation_gain_meters"
            ),
            "average_pace_seconds_per_km": state.get(
                "last_workout_average_pace_seconds_per_km"
            ),
            "route_match_percent": state.get(
                "last_workout_route_match_percent"
            ),
            "device": state.get("last_workout_route_device"),
            "route_point_count": state.get(
                "last_workout_route_point_count"
            ),
        }
        return {
            key: value
            for key, value in attributes.items()
            if value is not None
        }

    async def async_added_to_hass(self) -> None:
        """Refresh the camera whenever ATHLTH pushes new state."""
        await super().async_added_to_hass()
        self.async_on_remove(
            async_dispatcher_connect(
                self.hass,
                signal_update(self._entry_id),
                self.async_write_ha_state,
            )
        )
